project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - text: "About me"
        href: cv.qmd
      - text: "Artistic stuff"
        menu:
          - text: "Drawings and Paintings"
            href: art_drawings.qmd
          - text: "Crochet"
            href: art_crochet.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true